import = [
    "~/.config/alacritty/themes/themes/marine_dark.toml"
]

[font]
size = 10

[window]
opacity = 0.99

[keyboard]
bindings = [
    { key = "v", mods = "Alt", action = "Paste" },
    { key = "c", mods = "Alt", action = "Copy" }
]

[selection]
save_to_clipboard = true
